version: "3"
services:

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=serviceCatalog
      - MONGO_INITDB_ROOT_PASSWORD=adm?i=n
      - MONGO_INITDB_ROOT_USERNAME=root
    ports:
      - "27017:27017"
