version: "3"
services:

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=serviceCatalog
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=adm?i=n
    ports:
      - "5432:5432"
