logging:
  level.root: WARN
  level.no: ${LOG_LEVEL:DEBUG}
  level.org.springframework: WARN
  level.org.springframework.web: WARN
server:
  port: 8080
management:
  endpoint.health.probes.enabled: true
  health:
    livenessState.enabled: true
    readinessState.enabled: true
spring:
  mongodb:
    host: ${MONGODB_HOST}
    username: ${MONGO_USERNAME}
    password: ${MONGO_PASSWORD}
    authentication-database: ${MONGODB_AUTH}
    replica-set-name: ${MONGODB_REPLICASET}
    port: 27017
    database: serviceCatalog
  data:
    mongodb:
      auto-index-creation: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_OIDC_ISSUER}
          jwk-set-uri: ${KEYCLOAK_OIDC_ISSUER}/protocol/openid-connect/certs
application:
  serviceCatalogUri: ${SERVICE_CATALOG_URI}
  harvestAdminUri: ${ADMIN_API_BASE_URI}
  cors.originPatterns: "${CORS_ORIGIN_PATTERNS}"
---
spring:
  config.activate.on-profile: test
  mongodb:
    database: serviceCatalog
  data:
    mongodb:
      auto-index-creation: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:5050/auth/realms/fdk
          jwk-set-uri: http://localhost:5050/auth/realms/fdk/protocol/openid-connect/certs
application:
  serviceCatalogUri: http://localhost:5050
  harvestAdminUri: http://localhost:5050/harvest-admin
  cors.originPatterns: "*"
---
spring:
  config.activate.on-profile: dev
  mongodb:
    host: localhost
    username: root
    password: adm?i=n
    authentication-database: admin
    replica-set-name: null
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.staging.fellesdatakatalog.digdir.no/realms/fdk
          jwk-set-uri: https://auth.staging.fellesdatakatalog.digdir.no/realms/fdk/protocol/openid-connect/certs
application:
  serviceCatalogUri: http://localhost:8080
  harvestAdminUri: http://localhost:8081/harvest-admin
  cors.originPatterns: "*"
