logging:
  level.root: WARN
  level.no: ${LOG_LEVEL:DEBUG}
  level.org.springframework: WARN
  level.org.springframework.web: WARN
server:
  port: 8080
management:
  endpoint.health.probes.enabled: true
  health:
    livenessState.enabled: true
    readinessState.enabled: true
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/${POSTGRESQL_DB}
    username: ${POSTGRESQL_USER}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        type:
          json_format_mapper: no.digdir.servicecatalog.configuration.CustomJacksonJsonFormatMapper
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_OIDC_ISSUER}
          jwk-set-uri: ${KEYCLOAK_OIDC_ISSUER}/protocol/openid-connect/certs
application:
  serviceCatalogUri: ${SERVICE_CATALOG_URI}
  cors.originPatterns: "${CORS_ORIGIN_PATTERNS}"
---
spring:
  config.activate.on-profile: test
  datasource:
    url: jdbc:postgresql://localhost:5432/service_catalog
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:5050/auth/realms/fdk
          jwk-set-uri: http://localhost:5050/auth/realms/fdk/protocol/openid-connect/certs
application:
  serviceCatalogUri: http://localhost:5050
  cors.originPatterns: "*"
---
spring:
  config.activate.on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.staging.fellesdatakatalog.digdir.no/realms/fdk
          jwk-set-uri: https://auth.staging.fellesdatakatalog.digdir.no/realms/fdk/protocol/openid-connect/certs
application:
  serviceCatalogUri: http://localhost:8080
  cors.originPatterns: "*"
