logging:
  level.root: WARN
  level.no: ${LOG_LEVEL:DEBUG}
  level.org.springframework: WARN
  level.org.springframework.web: WARN
server:
  port: 8080
management:
  endpoint.health.probes.enabled: true
  health:
    livenessState.enabled: true
    readinessState.enabled: true
spring:
  data.mongodb.uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGODB_HOST}/serviceCatalog?authSource=${MONGODB_AUTH}&replicaSet=${MONGODB_REPLICASET}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SSO_HOST}/auth/realms/fdk
          jwk-set-uri: ${SSO_HOST}/auth/realms/fdk/protocol/openid-connect/certs
application:
  serviceCatalogUri: ${SERVICE_CATALOG_URI}
  cors.originPatterns: "${CORS_ORIGIN_PATTERNS}"
---
spring:
  config.activate.on-profile: test
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:5050/auth/realms/fdk
          jwk-set-uri: http://localhost:5050/auth/realms/fdk/protocol/openid-connect/certs
application:
  serviceCatalogUri: http://localhost:5050
  cors.originPatterns: "*"
---
spring:
  config.activate.on-profile: dev
  data.mongodb.uri: mongodb://root:admin@localhost:27017/serviceCatalog?authSource=admin&replicaSet=replicaset
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://sso.staging.fellesdatakatalog.digdir.no/auth/realms/fdk
          jwk-set-uri: https://sso.staging.fellesdatakatalog.digdir.no/auth/realms/fdk/protocol/openid-connect/certs
application:
  serviceCatalogUri: http://localhost:8080
  cors.originPatterns: "*"
