---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-catalog
  labels:
    app: service-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-catalog
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: service-catalog
      annotations:
        prometheus.io/scrape: "false"
    spec:
      containers:
        - name: service-catalog
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xmx1g -XX:+UseZGC -XX:MaxRAMPercentage=80.0"
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: service-catalog
                  key: MONGO_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: service-catalog
                  key: MONGO_PASSWORD
            - name: MONGODB_HOST
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: MONGODB_HOST
            - name: MONGODB_AUTH
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: MONGODB_AUTH
            - name: MONGODB_REPLICASET
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: MONGODB_REPLICASET
            - name: SSO_HOST
              valueFrom:
                secretKeyRef:
                  name: commonurl
                  key: SSO_BASE_URI
            - name: SERVICE_CATALOG_URI
              valueFrom:
                secretKeyRef:
                  name: commonurl
                  key: SERVICE_CATALOG_BASE_URI
            - name: CORS_ORIGIN_PATTERNS
              valueFrom:
                secretKeyRef:
                  name: service-catalog
                  key: CORS_ORIGIN_PATTERNS
          image: service-catalog
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
          resources:
            requests:
              memory: 1000Mi
