---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment-service-catalog.yaml
  - service-service-catalog.yaml
images:
  - name: service-catalog
    newName: ghcr.io/informasjonsforvaltning/service-catalog
    newTag: $(GIT_COMMIT_SHA)
